import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { NavbarIjac } from "./components/Navbarijac";
import Footer from "./components/Footer";
import WhatsApp from "./components/WhatsApp";

import { HamburgerMenu } from "./components/HamburgerMenu";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <body
        className={`${inter.variable} ${spaceGrotesk.variable} font-sans antialiased`}
      >
       <div className="hidden md:block">
         <NavbarIjac />
       </div>
       <div className="block md:hidden">
         <HamburgerMenu />
       </div>
        {children}
        <WhatsApp />
        <Footer />
      </body>
    </html>
  );
}
